config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  get 'home', to: 'pages#home', as: 'home'
  get 'about', to: 'pages#about', as: 'about'
  get 'my_work', to: 'pages#my_work', as: 'my_work'
  get 'contact', to: 'pages#contact', as: 'contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        render :home
    end

    def about
        render :about
    end

    def my_work
        render :my_work
    end

    def contact
        render :contact
    end
end

app/controllers/work_controller.rb
class WorkController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Greatest Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <style>
      nav {
        background-color: rgb(0, 160, 160);
        padding: 15px;
        font-family: Arial, Helvetica, sans-serif;
        font-size: 18px;
      }
      
      nav ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
      }
      nav ul li {
        display: inline;
        margin-right: 15px;
      }
      
      nav ul li:last-child {
        margin-right: 0;
      }
      
      nav ul li a {
        color: black;
        text-decoration: none;
      }
    </style>
    
    <nav>
      <ul>
        <li><%= link_to 'Home', home_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'My Work', my_work_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!--...-->


<div class="container">
    <section class="biography">
        <h1>Biography</h1>
        <ul>
            <li>
                Experienced developer with over a millennia (that's over a thousand years -- wow!)
                of expertise in every field imaginable
            </li>
            <li>
                Proficient in pretty much any and every front-end technology you can think of -- except that one, 
                because that one doesn't matter. Yeah, sorry.
            </li>
            <li>
                Strong problem-solving abilities (how else could I live for so long?) and a keen eye for detail
            </li>
        </ul>
    </section>

    <section class="image">
        <%= image_tag "brain.jpg", class: "portfolio-image" %>
    </section>

    <section class="education">
        <h2>Educational Background</h2>
        <ul>
            <li>
                Attended lectures at the University of Oxford in England during the Middle Ages 
                (12th century onwards -- believe me, it was less than ideal)
            </li>
            <li>
                Studied at Plato's Academy in Athens, Greece, during the Classical period 
                (4th century BCE -- quite a nice fellow that Plato gentleman)
            </li>
            <li>
                Earned a degree in Time Travel Physics from the 22nd Century Institute of Temporal Mechanics 
                (don't ask me about this one, I signed an NDA)
            </li>
        </ul>
    </section>

    <section class="image">
        <%= image_tag "plato_academy.jpg", class: "portfolio-image" %>
    </section>

    <section class="skills">
        <h3>Skills</h3>
        <ul>
            <li>
                Developed the 1st-ever JavaScript library that reads users' minds (Professor X style) which determines what they want to search for before they even start typing.
            </li>
            <li>
                Created a framework for CSS that predicts the future and adapts the styling based on upcoming trends, which ensures your site/app remains pretty(!) forever (who wouldn't want this).
            </li>
            <li>
                Invented a server architecture which is so advanced it eliminates the need for physical OR virtual servers and runs entirely on cosmic background radiation (I heard about cosmic background radition in The Three-Body Problem, so you know you can trust that I know all there is to know about it).
            </li>
        </ul>
    </section>

    <section class="image">
        <%= image_tag "prof_x.jpg", class: "portfolio-image" %>
    </section>

    <section class="achievements">
        <h4>Achievements</h4>
        <ul>
            <li>2030 FIFA World Cup winner! (What does this have to do with web dev? Who cares! Football is the world's sport.)</li>
            <li>Received the Pulitzer Prize for Code! (To be honest, I didn't even know that this existed. Wait... it does exist, right? Anyways...) They recognized me for writing the world's most poetic code, which has been published/studied worldwide, naturally.</li>
            <li>Receieved a neato swag bag for attending a developer conference. (Hey, they don't give those out to just anyone!)</li>
        </ul>
    </section>

    <section class="image">
        <%= image_tag "world_cup.jpg", class: "portfolio-image" %>
    </section>
</div>

app/views/pages/contact.html.erb
<!--...-->


<div class="container">
    <section class="contact-form">
        <p>
            I assume if you're here to fill out this contact form, then you must have already seen how awesome I am.
            If you haven't, then what are you waiting for? Go check me out!
        </p>
        
        <form>
            <label for="name">Name:</label><br>
            <input type="text" id="name" name="name" required><br><br>
            
            <label for="email">Email:</label><br>
            <input type="email" id="email" name="email" required><br><br>
            
            <label for="subject">Subject:</label><br>
            <input type="text" id="subject" name="subject" required><br><br>
            
            <label for="message">Message:</label><br>
            <textarea id="message" name="message" required></textarea><br><br>
            
            <button type="submit">Send</button><br>
        </form>
    </section>
</div>

app/views/pages/home.html.erb
<!--...-->


<div class="container">
    <section class="intro">
        <h1>Welcome to the Best Portfolio on the Web!</h1>
        <p>
            Prepare to be blown away by the most impressive introductory paragraph you've ever read. 
            My skills (clearly) are unparalleled, my talent (of course) is unmatched, and my modesty 
            (certainly) is unquestionable. I am 100% confident that browsing my portfolio will leave 
            you wanting to employ me immediately over any and every other developer on planet Earth.
        </p>
    </section>

    <section class="image">
        <%= image_tag "goat.jpg", class: "portfolio-image" %>
    </section>

    <section class="expertise">
        <h2>My Expertise (The Best Expert Who Ever Expert-ed)</h2>
        <p>
            I specialize in whatever you are looking for. For an unbelievable amount of years 
            (impossible, some might say, but I assure you it's definitely true), I have dedicated 
            myself to being an expert in the field of doing-awesome-things. If you need a website that will 
            make your competition cry and close up shop, I'm your guy. If you need an app that will blow up 
            the market (in a good way!), then look no further. You've come to the right place, if you need 
            a solution to a problem that hasn't even been discovered yet. With that, I shall leave you so 
            that you make soak it all in. Enjoy (how could you not)!
        </p>
    </section>
</div>

app/views/pages/my_work.html.erb
<!--...-->


<div class="container">
    <section class="project-1">
        <h1>WebSNES: The NES and SNES Web Emulator</h1>
        <ul>
            <li>
                Uses JavaScript for the emulation logic, which simulates the CPU, the memory, and the sound systems of both the NES and SNES consoles.
            </li>
            <li>
                Makes use of the HTML5 Canvas to render games in the browser, while also preserving the original look and feel of the games.
            </li>
            <li>
                Implements a secure system to load the games' ROMs through safe user uploads.
            </li>
        </ul>
    </section>

    <section class="image">
        <%= image_tag "lttp.jpg", class: "portfolio-image" %>
    </section>

    <section class="project-2">
        <h2>Totally Not Skynet (So Don't Worry)</h2>
        <ul>
            <li>
                Created the very 1st AI that passes the Turing Test (those other guys are lying).
            </li>
            <li>
                Transforms normal and everyday cloud computing into the 1st sentient, self-aware network capable of optimizing itself in real-time (relax, we're not in any danger).
            </li>
            <li>
                Uses flux processors (shout out to Doc Brown!): a new processor which uses synthetic synapses to increase computational speed/efficiency.
            </li>
        </ul>
    </section>

    <section class="image">
        <%= image_tag "irobot.jpg", class: "portfolio-image" %>
    </section>
</div>